language: ruby
rvm:
  - 1.9.3
script: rake test

notifications:
  webhooks:
    - http://rcmp.programble.co.cc/irc.tenthbit.net/programming
    - http://rcmp.programble.co.cc/irc.freenode.net/sicuro
  
  email:
    on_success: change # default: change
    on_failure: change # default: always

